In [8]:
import numpy as np

## Vectorization: Fixing the Loop Problem

In [11]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


## Broadcasting: 
Scaling Arrays Without Extra Memory

In [16]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


### Broadcasting with Arrays of Different Shapes

#### Broadcasting with Two Arrays

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


### Broadcasting a 2D Array and a 1D Array

In [36]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)


[[2 4 6]
 [5 7 9]]


## Hands-on: Applying Broadcasting to Real-World Scenarios
Let’s apply broadcasting to a real-world scenario: scaling data in machine learning.


### Example: Normalizing Data Using Broadcasting
Imagine you have a dataset where each row represents a sample and each column represents a feature. 
You can normalize the data by subtracting the mean of each column and dividing by the standard deviation.

In [65]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print("mean : ",mean)
print("std : ",std)

print("normalized_data :\n", normalized_data )


mean :  [20. 30. 40.]
std :  [7.07106781 7.07106781 7.07106781]
normalized_data :
 [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
