## Creating NUMpy Array


In [4]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])

print(type(arr1))   # <class 'numpy.ndarray'>
print(arr2.shape)   # Dimenssion

print(arr1)

arr2

<class 'numpy.ndarray'>
(2, 3)
[1 2 3 4]


array([[1, 2, 3],
       [4, 5, 6]])

## From Seratch

#### n*m array of 0  ---> np.zeros((n,m))

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### n*m array of 0 ---> np.ones((n,m))

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### n*m array filled with x ---> np.full((n,m),x)

In [15]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### n*n Identity Matrix ---->np.eye(n)

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### like Range ----> np.arange(start, stop, step)

In [21]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

#### Evenly Spaced -----> np.linspace(start, stop, num)
##### it gives Evenly Spaced Array with 'num' of elements in it

In [24]:
np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Array Properties

In [29]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[9,5,1]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 5, 1]])

#### arr.shape ----> (row, column)

In [32]:
# Shape
arr3.shape

(4, 3)

#### arr.size ------> Total nUmber of Elements 

In [35]:
arr3.size

12

#### arr.ndim ----> dimension of array

In [38]:
arr3.ndim

2

#### dtype -----> int64 (int 34 for windowds)

In [41]:
arr3.dtype

dtype('int32')

## Changing Data Types

In [44]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32
 

float32


### .astype(np.typename)

In [46]:
arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

[1 2 3]


##  Reshaping and Flattening Arrays

#### Reshaped

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)
 
reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


#### convert 2d --> 1D

In [52]:
flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [14]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr[0]

array([1, 2, 3])