### Changing Data Types

In [4]:
import numpy as np
arr = np.array([1.3,2.5,3.1,4.7,5.6])
print(arr.dtype)
arr

float64


array([1.3, 2.5, 3.1, 4.7, 5.6])

In [6]:
arr_int = arr.astype(np.int64)
print(arr_int)
print(arr_int.dtype)

[1 2 3 4 5]
int64


### Downcasting to Save Memory

In [9]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


## Memory Usage

In [22]:
arr64 = np.array([1,2,3,4], dtype = np.int64)
arr32 = np.array([1,2,3,4], dtype = np.int32)

print(arr64.nbytes)
print(arr32.nbytes)

32
16


## String Array

In [27]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)
print(arr.dtype)

['apple' 'banana' 'cherry']
<U10


## Complex Numbers

In [30]:
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


## Object Data Type

In [35]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)
print(arr.dtype)

[{'a': 1} list([1, 2, 3]) 'hello']
object
