### Create a 3×3 array filled with random numbers and print its shape.

In [8]:
import numpy as np

arr = np.random.rand(3,3)

print(arr)

[[0.49676468 0.97428731 0.89724594]
 [0.44237882 0.20100035 0.64581401]
 [0.64799279 0.82226207 0.60467323]]


### Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [17]:
arr = np.array([1.1,2.2,3.3], dtype = "int")
print(arr.dtype)

int32


### Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])
id = (arr%2 ==0)
print(arr[id])

[2 4 6]


### Reshape a 1D array of size 9 into a 3×3 matrix.

In [34]:
arr = np.arange(1,10)

arr.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Use boolean masking to filter numbers greater than 50 in an array.

In [43]:
arr = np.random.randint(10,100,(3,3))

mask = arr> 50

print(arr[mask])

[82 77 83 51 53 77]
