## Indexing (Same as Python Lists)


In [10]:
import numpy as np 
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


## Slicing (Extracting Parts of an Array)

In [13]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


### Slicing returns a view, not a copy! Changes affect the original array.**


This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

Why does this happen?

Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.

Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [25]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


### Use .copy() if you need an independent copy.

In [34]:
rr = np.array([10, 20, 30, 40, 50])

slice = rr[1:4].copy()
slice[0] = 999
print(rr)  # [10 20 30 40 50]

[10 20 30 40 50]


## Fancy Indexing & Boolean Masking

### Fancy Indexing (Select Multiple Elements)

In [52]:
arr = np.array([10, 20, 30, 40, 50])

idx = [0,2,4]

print(arr[idx])
arr[idx]

[10 30 50]


array([10, 30, 50])

### Boolean Masking (Filter Data)

In [57]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]
