### Understanding Axes in NumPy


Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)

2D array → 2 axes (axis 0 = rows, axis 1 = columns)

3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [7]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Axis 0 (rows) → Operations move down the columns.

In [10]:
print(np.sum(arr, axis = 0))

[12 15 18]


### Axis 1 (columns) → Operations move across the rows.

In [13]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

## Indexing in Multidimensional Arrays

#### You can access elements using row and column indices.

In [17]:
# Accessing an element
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6

6


#### You can also use slicing to extract parts of an array:

In [20]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


## Indexing in 3D Arrays

#### For 3D arrays, the first index refers to the "depth" (sheets of data).

In [24]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


### Accessing elements in 3D:

#### First sheet, second row, third column

In [30]:
print(arr3D[0, 1, 2])  # Output: 6

6


#### Get the first row from both sheets

In [33]:
print(arr3D[:, 0, :])   

[[1 2 3]
 [7 8 9]]


## Practical Example: Selecting Data Along Axes

#### Get all rows of the first column

In [40]:
first_col = arr[:,0]
first_col

array([1, 4, 7])

#### Get the first row from each "sheet" in a 3D array

In [43]:
first_row = arr3D[:,0,:]
first_row

array([[1, 2, 3],
       [7, 8, 9]])

## Changing Data Along an Axis

#### Replace all elements in column 1 with 0

In [51]:
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
